// Code generated by rlpgen. DO NOT EDIT.

//go:build !norlpgen
// +build !norlpgen

package types

import "github.com/kardiachain/go-kardia/lib/rlp"
import "io"

func (obj *Header) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteUint64(obj.Height)
	_tmp1 := w.List()
	w.ListEnd(_tmp1)
	w.WriteUint64(obj.NumTxs)
	w.WriteUint64(obj.GasLimit)
	_tmp2 := w.List()
	w.WriteBytes(obj.LastBlockID.Hash[:])
	_tmp3 := w.List()
	w.WriteUint64(uint64(obj.LastBlockID.PartsHeader.Total))
	w.WriteBytes(obj.LastBlockID.PartsHeader.Hash[:])
	w.ListEnd(_tmp3)
	w.ListEnd(_tmp2)
	w.WriteBytes(obj.ProposerAddress[:])
	w.WriteBytes(obj.LastCommitHash[:])
	w.WriteBytes(obj.TxHash[:])
	w.WriteBytes(obj.ValidatorsHash[:])
	w.WriteBytes(obj.NextValidatorsHash[:])
	w.WriteBytes(obj.ConsensusHash[:])
	w.WriteBytes(obj.AppHash[:])
	w.WriteBytes(obj.EvidenceHash[:])
	w.ListEnd(_tmp0)
	return w.Flush()
}
