// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DualMessage.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message is sent from the dual node to kardia when it receive a trigger smart contract transaction.
type Message struct {
	TransactionId        string   `protobuf:"bytes,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	ContractAddress      string   `protobuf:"bytes,2,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	MethodName           string   `protobuf:"bytes,3,opt,name=methodName,proto3" json:"methodName,omitempty"`
	Params               []string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
	Amount               uint64   `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Sender               string   `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,7,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	Timestamp            uint64   `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_d39388d70c7d589d, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *Message) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *Message) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *Message) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Message) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Message) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Message) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *Message) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "protocol.Message")
}

func init() { proto.RegisterFile("DualMessage.proto", fileDescriptor_d39388d70c7d589d) }

var fileDescriptor_d39388d70c7d589d = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd0, 0xbf, 0x4a, 0xc4, 0x40,
	0x10, 0x06, 0x70, 0x72, 0x17, 0xf3, 0x67, 0x44, 0xc4, 0x2d, 0x64, 0x05, 0x91, 0x20, 0x16, 0xa9,
	0xae, 0xf1, 0x09, 0x3c, 0x6c, 0x2c, 0xbc, 0x22, 0xa5, 0xdd, 0x64, 0x77, 0x39, 0x0f, 0xb3, 0x3b,
	0x61, 0x76, 0xf2, 0x00, 0xbe, 0xb9, 0x64, 0x0d, 0x18, 0xaf, 0x5a, 0xbe, 0xdf, 0xcc, 0x4e, 0xf1,
	0xc1, 0xcd, 0xeb, 0x84, 0xc3, 0xbb, 0x8b, 0x11, 0x8f, 0x6e, 0x37, 0x32, 0x09, 0xa9, 0x2a, 0x3d,
	0x86, 0x86, 0xc7, 0xef, 0x0d, 0x94, 0xcb, 0x4c, 0x3d, 0xc1, 0x95, 0x30, 0x86, 0x88, 0x46, 0x4e,
	0x14, 0xde, 0xac, 0xce, 0x9a, 0xac, 0xad, 0xbb, 0xff, 0xa8, 0x5a, 0xb8, 0x36, 0x14, 0x84, 0xd1,
	0xc8, 0x8b, 0xb5, 0xec, 0x62, 0xd4, 0x9b, 0xb4, 0x77, 0xce, 0xea, 0x01, 0xc0, 0x3b, 0xf9, 0x24,
	0x7b, 0x40, 0xef, 0xf4, 0x36, 0x2d, 0xad, 0x44, 0xdd, 0x42, 0x31, 0x22, 0xa3, 0x8f, 0x3a, 0x6f,
	0xb6, 0x6d, 0xdd, 0x2d, 0x69, 0x76, 0xf4, 0x34, 0x05, 0xd1, 0x17, 0x4d, 0xd6, 0xe6, 0xdd, 0x92,
	0x66, 0x8f, 0x2e, 0x58, 0xc7, 0xba, 0x48, 0xb7, 0x96, 0xa4, 0x1a, 0xb8, 0xec, 0x07, 0x32, 0x5f,
	0x87, 0xc9, 0xf7, 0x8e, 0x75, 0x99, 0x3e, 0xad, 0x49, 0xdd, 0x43, 0x2d, 0x27, 0xef, 0xa2, 0xa0,
	0x1f, 0x75, 0x95, 0xe6, 0x7f, 0xb0, 0xbf, 0x83, 0x8a, 0xf8, 0xb8, 0x13, 0xa6, 0xb0, 0xcf, 0xe7,
	0xb2, 0x3e, 0x4a, 0xff, 0x5b, 0x49, 0x5f, 0xa4, 0xa2, 0x9e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x50, 0x2e, 0x74, 0xd2, 0x44, 0x01, 0x00, 0x00,
}
