# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
# - "alert.rules"
# - "first.rules"
# - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: node1-prometheus
    static_configs:
      - targets: ['node1:6001']
  - job_name: node2-prometheus
      static_configs:
        - targets: [ 'node2:6002' ]
  - job_name: node3-prometheus
      static_configs:
        - targets: [ 'node3:6003' ]