Node:
  Name: node1
  DataDir: /tmp/.kardia
  HTTPHost: 0.0.0.0
  HTTPPort: 8545
  HTTPModules:
    - node
    - kai
    - tx
    - account
    - dual
    - neo
  HTTPVirtualHosts:
    - 0.0.0.0
    - localhost
  HTTPCors:
    - "*"
  P2P:
    PrivateKey: 8843ebcb1021b00ae9a644db6617f9c6d870e5fd53624cefe374c1d2d710fd06
    ListenAddress: tcp://0.0.0.0:3000
    MaxPeers: 25
  LogLevel: info           # crit, error, warn, info, debug, trace
  Metrics: 1
MainChain:
  ServiceName: KARDIA
  ChainId: 1
  NetworkId: 10000
  AcceptTxs: 1       # accept tx sync process or not (1 is yes, 0 is no)
  Seeds:
    - c1fe56e3f58d3244f606306611a5d10c8333f1f6@127.0.0.1:3000
    - 7cefc13b6e2aedeedfb7cb6c32457240746baee5@127.0.0.1:3001
    - ff3dac4f04ddbd24de5d6039f90596f0a8bb08fd@127.0.0.1:3002
  Database:
    Dir: chaindata                           # directory stores leveldb
    Cache: 16                                # cache is used in leveldb
    Handles: 32                              # handles is used in leveldb
    Drop: 1                                  # Specify whether drop database or not (0 is no, 1 is yes)
GenTxs: # Devnet config to dynamize txs processing
  Type: 1
  NumTxs: 500
  Delay: 2
  Index: 1
Debug: # Devnet config for debugging purposes 
  Port: ":6000"